// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoC-A2a8Bq0fDGmPuMTnnKedkTT-RmJqM',
    appId: '1:243450137665:web:2f41fd7046f43ab9bbcac0',
    messagingSenderId: '243450137665',
    projectId: 'api-key-7955d',
    authDomain: 'api-key-7955d.firebaseapp.com',
    databaseURL: 'https://api-key-7955d-default-rtdb.firebaseio.com',
    storageBucket: 'api-key-7955d.appspot.com',
    measurementId: 'G-Y5G9ZJTM93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAROf28qmYys0QOyIms9Aodp9BZF1vdv9A',
    appId: '1:243450137665:android:28529d65f5f6b2b3bbcac0',
    messagingSenderId: '243450137665',
    projectId: 'api-key-7955d',
    databaseURL: 'https://api-key-7955d-default-rtdb.firebaseio.com',
    storageBucket: 'api-key-7955d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu5B_XgVpWjcHv6gApLK8G8PrveEtN4ls',
    appId: '1:243450137665:ios:cd3213ad971db1b1bbcac0',
    messagingSenderId: '243450137665',
    projectId: 'api-key-7955d',
    databaseURL: 'https://api-key-7955d-default-rtdb.firebaseio.com',
    storageBucket: 'api-key-7955d.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );
}
