name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get API Key
      run: |
        export OPENAI_API_KEY=${{ secrets.API_KEY }}
        export NAVER_CLOVA_API_KEY=${{ secrets.NAVER_CLOVA_API }}
        echo "const String GPT_API = '${{ secrets.API_KEY }}';" >> foodapp/lib/Pages/gpt.dart
        echo "const String NAVER_CLOVA_API = '${{ secrets.NAVER_CLOVA_API }}';" >> foodapp/lib/Pages/receipt_ocr.dart
    - name: Print API Key
      run: |
        echo "OPENAI_API_KEY: ${{ secrets.API_KEY }}"
        echo "NAVER_CLOVA_API_KEY: ${{ secrets.NAVER_CLOVA_API }}"

    - name: Build Flutter App
      env: 
        OPENAI_API_KEY: ${{ secrets.API_KEY }}
        NAVER_CLOVA_API_KEY: ${{ secrets.NAVER_CLOVA_API }}
      run: |
        cd foodapp
        flutter pub get
        flutter build apk --release --target lib/main.dart
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./foodapp/build/app/outputs/flutter-apk/app-release.apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.COOLFRIDGE }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload APK to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.COOLFRIDGE }}
      with:
        upload_url: https://github.com/GDSC-DJU/24SolChl_CoolFridge/releases
        asset_path: ./foodapp/build/app/outputs/flutter-apk/app-release.apk
        asset_name: CoolFridge.apk
        asset_content_type: application/vnd.android.package-archive
