name: Flutter Build

# 워크플로우를 실행할 이벤트를 지정합니다. push 이벤트가 발생할 때만 워크플로우가 실행됩니다.
on:
  push:
    branches:
      - stage2

# 워크플로우의 작업을 정의합니다.
jobs:
  build:
    # 작업을 실행할 환경을 지정합니다. 여기서는 최신 버전의 Ubuntu를 사용합니다.
    runs-on: ubuntu-latest
    
    # 작업의 단계를 정의합니다.
    steps:
    - name: Checkout repository
      # GitHub 저장소를 체크아웃하는 작업입니다.
      uses: actions/checkout@v2
      
    - name: Set up Flutter
      # Flutter를 설정하는 작업입니다. subosito/flutter-action 액션을 사용합니다.
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9' # 원하는 버전으로 설정
        
    - name: Get API Key
      # GitHub 저장소의 Secrets에서 API 키를 가져와서 파일에 저장하는 작업입니다.
      run: echo ${{ secrets.API_KEY }} > api_key.txt
      
    - name: Build Flutter App
      # Flutter 앱을 빌드하는 작업입니다. release APK를 생성합니다.
      run: flutter build apk --release
      
    - name: Deploy
      # 앱을 배포하는 작업입니다. 여기에는 배포에 필요한 단계가 추가될 수 있습니다.
