name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 기존 Flutter 빌드 작업
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        
    - name: Get API Key
      run: |
        export OPENAI_API_KEY=\"${{ secrets.API_KEY }}\"
        export NAVER_CLOVA_API_KEY=\"${{ secrets.NAVER_CLOVA_API }}\"
      
    - name: Build Flutter App
      run: |
        cd foodapp
        flutter pub get
        flutter build apk --release --target lib/main.dart

    # 새로 추가한 APK 생성 작업
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./foodapp/build/app/outputs/flutter-apk/app-release.apk

   

    # 릴리즈 생성 및 APK 업로드 작업
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.COOLFRIDGE }}
      with:
        tag_name: v1.0.9
        release_name: Release v1.0.9
        draft: false
        prerelease: false

    - name: Upload APK to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.COOLFRIDGE }}
      with:
        upload_url: https://github.com/GDSC-DJU/24SolChl_CoolFridge/releases
        asset_path: ./foodapp/build/app/outputs/flutter-apk/app-release.apk
        asset_name: CoolFridge.apk
        asset_content_type: application/vnd.android.package-archive
